yaml
name: Unity Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: develop
      
    - name: Setup Unity
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: '2020.3.12f1' # ここに使用しているUnityのバージョンを指定してください。

    - name: Run tests
      run: |
        echo "Running Unity tests..."
        chmod +x ./test.sh
        ./test.sh
